import type { Metadata} from "next";
import "../global.css"
import Image from "next/image";
import Link from "next/link";
import realceimage from "./home/realcehotel.png"
import Footer from "../(components)/footer/page";
export const metadata: Metadata = {
  title: "Hotel em jaú | Realce Hotel",
  description: "Generated by create next app",

  
};

export default function PublicLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>   
       <header className="bg-zinc-800 flex justify-center ">
                    <Image className="bg-white-200" src={realceimage}  alt="logo da pagina" width={300} 
                    height={100}/>
                    <nav  >
                        <ul className="flex  gap-5 p-20 text-white">
                            <li><button className="bg-zinc-500 hover:bg-sky-700 ... w-20 h-10">Reservas</button></li>
                            <li><button className="bg-zinc-500 hover:bg-sky-700 ... w-20 h-10">Check-in</button></li>
                        </ul>
                    </nav>
                </header>
                 <nav className="p-5 bg-zinc-700 ...">
                    <ul className="flex justify-evenly text-white ...">
                        <li><Link href="/home"><button className="bg-white-600 hover:bg-sky-500 ... w-20 h-10 ">Home</button></Link></li>
                        <Link href="/contato"><li><button className="bg-white-600 hover:bg-sky-500 ... w-30 h-10">Quem Somos</button></li></Link>
                        <li><button className="bg-white-600 hover:bg-sky-500 ... w-30 h-10">Acomodações</button></li>
                        <li><button className="bg-white-600 hover:bg-sky-500 ... w-20 h-10">Fotos</button></li>
                        <li><button className="bg-white-600 hover:bg-sky-500 ... w-20 h-10">Contato</button></li>
                    </ul>
                 </nav> 
                 

        {children}

      <Footer/>
    </div>

  );
}
